namespace Protocol.Minecraft;

public enum PlayerAction
{
	StartBreak = 0,
	AbortBreak = 1,
	StopBreak = 2,
	GetUpdatedBlock = 3,
	DropItem = 4,
	StartSleeping = 5,
	StopSleeping = 6,
	Respawn = 7,
	Jump = 8,
	StartSprint = 9,
	StopSprint = 10,
	StartSneak = 11,
	StopSneak = 12,
	CreativeDestroy = 13,
	DimensionChangeAck = 14,
	StartGlide = 15,
	StopGlide = 16,
	WorldImmutable = 17,
	Breaking = 18,
	ChangeSkin = 19,
	SetEnchantmentSeed = 20,
	StartSwimming = 21,
	StopSwimming = 22,
	StartSpinAttack = 23,
	StopSpinAttack = 24,
	InteractBlock = 25,
	PredictDestroyBlock = 26,
	ContinueDestroyBlock = 27,
	StartItemUse = 28,
	StopItemUse = 29,
	HandledTeleport = 30,
	MissedSwing = 31,
	StartCrawling = 32,
	StopCrawling = 33,
	StartFlying = 34,
	StopFlying = 35,
	ClientAckServerData = 36,
	StartUsingItem = 37
}